-- =============================================================================
-- Migration 005: Sample property listings with AI-generated images
-- 3 sale_freehold, 3 sale_leasehold, 3 short_term_rent
-- =============================================================================

-- Sale Freehold
INSERT INTO properties (owner_id, title, slug, description, property_type, listing_type, price, price_period, currency, area, address, bedrooms, bathrooms, land_size_sqm, building_size_sqm, features, images, thumbnail_url, is_active, is_featured) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Modern Luxury Villa with Infinity Pool in Canggu', 'modern-luxury-villa-canggu', 'Stunning 4-bedroom contemporary villa featuring an infinity pool overlooking rice fields, open-plan living spaces, fully equipped gourmet kitchen, and tropical gardens. Located in the heart of Canggu, minutes from Echo Beach and trendy cafes.', 'villa', 'sale_freehold', 950000, NULL, 'USD', 'Canggu', 'Jl. Pantai Batu Bolong, Canggu', 4, 4, 500, 380, '["Private Pool", "Rice Field View", "Fully Furnished", "Tropical Garden", "Parking", "Security"]'::jsonb, '["/images/listings/modern-luxury-villa-canggu-1.jpg", "/images/listings/modern-luxury-villa-canggu-2.jpg", "/images/listings/modern-luxury-villa-canggu-3.jpg"]'::jsonb, '/images/listings/modern-luxury-villa-canggu-1.jpg', true, true);

INSERT INTO properties (owner_id, title, slug, description, property_type, listing_type, price, price_period, currency, area, address, bedrooms, bathrooms, land_size_sqm, building_size_sqm, features, images, thumbnail_url, is_active, is_featured) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Beachfront Estate with Ocean Views in Uluwatu', 'beachfront-estate-uluwatu', 'Magnificent 5-bedroom clifftop estate with panoramic Indian Ocean views. Features a private cinema room, rooftop sunset lounge, 20-meter infinity pool, and direct cliff access. Premium Uluwatu location near top surf breaks.', 'villa', 'sale_freehold', 2800000, NULL, 'USD', 'Uluwatu', 'Jl. Labuansait, Pecatu', 5, 6, 1200, 850, '["Ocean View", "Infinity Pool", "Home Cinema", "Rooftop Lounge", "Staff Quarters", "Security"]'::jsonb, '["/images/listings/beachfront-estate-uluwatu-2.jpg", "/images/listings/beachfront-estate-uluwatu-3.jpg"]'::jsonb, '/images/listings/beachfront-estate-uluwatu-2.jpg', true, true);

INSERT INTO properties (owner_id, title, slug, description, property_type, listing_type, price, price_period, currency, area, address, bedrooms, bathrooms, land_size_sqm, features, images, thumbnail_url, is_active, is_featured) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Prime Investment Land in Seminyak', 'prime-land-seminyak', 'Rare 800sqm freehold land in prime Seminyak location, perfect for boutique hotel or villa development. Flat terrain with road access, electricity and water connected. Walking distance to Seminyak Beach.', 'land', 'sale_freehold', 1600000, NULL, 'USD', 'Seminyak', 'Jl. Kayu Aya, Seminyak', 0, 0, 800, '["Freehold Title", "Flat Terrain", "Road Access", "Near Beach", "Electricity", "Water"]'::jsonb, '["/images/listings/prime-land-seminyak-1.jpg"]'::jsonb, '/images/listings/prime-land-seminyak-1.jpg', true, true);

-- Sale Leasehold
INSERT INTO properties (owner_id, title, slug, description, property_type, listing_type, price, price_period, currency, area, address, bedrooms, bathrooms, land_size_sqm, building_size_sqm, features, images, thumbnail_url, is_active, is_featured) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Stylish 3BR Villa with Pool in Pererenan', 'stylish-villa-pererenan', 'Beautifully designed 3-bedroom villa on a 25-year leasehold. Features a private pool, open-plan kitchen, outdoor shower, and lush tropical garden. Located in up-and-coming Pererenan, 5 minutes from the beach.', 'villa', 'sale_leasehold', 280000, NULL, 'USD', 'Pererenan', 'Jl. Pantai Pererenan', 3, 3, 300, 220, '["Private Pool", "Tropical Garden", "Fully Furnished", "Outdoor Shower", "WiFi", "AC"]'::jsonb, '["/images/listings/stylish-villa-pererenan-1.jpg", "/images/listings/stylish-villa-pererenan-2.jpg", "/images/listings/stylish-villa-pererenan-3.jpg"]'::jsonb, '/images/listings/stylish-villa-pererenan-1.jpg', true, true);

INSERT INTO properties (owner_id, title, slug, description, property_type, listing_type, price, price_period, currency, area, address, bedrooms, bathrooms, land_size_sqm, building_size_sqm, features, images, thumbnail_url, is_active, is_featured) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Cozy 2BR Villa near Ubud Rice Terraces', 'cozy-villa-ubud-terraces', 'Enchanting 2-bedroom villa surrounded by rice paddies on a 30-year lease. Features traditional Balinese architecture, yoga deck, and a plunge pool overlooking the terraces. Perfect retreat for nature lovers.', 'villa', 'sale_leasehold', 180000, NULL, 'USD', 'Ubud', 'Jl. Raya Tegallalang, Ubud', 2, 2, 400, 160, '["Rice Field View", "Plunge Pool", "Yoga Deck", "Traditional Architecture", "Garden", "WiFi"]'::jsonb, '["/images/listings/cozy-villa-ubud-terraces-1.jpg", "/images/listings/cozy-villa-ubud-terraces-2.jpg", "/images/listings/cozy-villa-ubud-terraces-3.jpg"]'::jsonb, '/images/listings/cozy-villa-ubud-terraces-1.jpg', true, true);

INSERT INTO properties (owner_id, title, slug, description, property_type, listing_type, price, price_period, currency, area, address, bedrooms, bathrooms, building_size_sqm, features, images, thumbnail_url, is_active, is_featured) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Modern Apartment Complex in Sanur', 'modern-apartment-sanur', 'Brand new 1-bedroom apartment in a modern complex with communal pool and gym. 20-year leasehold with option to extend. Walking distance to Sanur Beach promenade and international schools.', 'apartment', 'sale_leasehold', 95000, NULL, 'USD', 'Sanur', 'Jl. Danau Tamblingan, Sanur', 1, 1, 55, '["Communal Pool", "Gym", "Security 24/7", "Near Beach", "Parking", "Furnished"]'::jsonb, '["/images/listings/modern-apartment-sanur-1.jpg"]'::jsonb, '/images/listings/modern-apartment-sanur-1.jpg', true, true);

-- Short-Term Rent
INSERT INTO properties (owner_id, title, slug, description, property_type, listing_type, price, price_period, currency, area, address, bedrooms, bathrooms, land_size_sqm, building_size_sqm, features, images, thumbnail_url, is_active, is_featured) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Tropical Pool Villa - Daily Rental in Canggu', 'tropical-pool-villa-daily-canggu', 'Perfect holiday villa with 3 bedrooms, private pool, and outdoor living pavilion. Located in central Canggu, walking distance to restaurants, shops, and surf spots. Includes daily housekeeping and breakfast.', 'villa', 'short_term_rent', 3500000, 'per_night', 'IDR', 'Canggu', 'Jl. Batu Mejan, Canggu', 3, 3, 350, 250, '["Private Pool", "Daily Housekeeping", "Breakfast Included", "WiFi", "AC", "Smart TV"]'::jsonb, '["/images/listings/tropical-pool-villa-daily-canggu-1.jpg", "/images/listings/tropical-pool-villa-daily-canggu-2.jpg", "/images/listings/tropical-pool-villa-daily-canggu-3.jpg"]'::jsonb, '/images/listings/tropical-pool-villa-daily-canggu-1.jpg', true, true);

INSERT INTO properties (owner_id, title, slug, description, property_type, listing_type, price, price_period, currency, area, address, bedrooms, bathrooms, land_size_sqm, building_size_sqm, features, images, thumbnail_url, is_active, is_featured) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Romantic Rice Field Retreat in Ubud', 'romantic-rice-field-retreat-ubud', 'Intimate 1-bedroom luxury retreat surrounded by rice paddies. Features an outdoor bathtub, private plunge pool, and breathtaking views. Ideal for couples seeking a unique Bali experience. Breakfast and spa credit included.', 'villa', 'short_term_rent', 2800000, 'per_night', 'IDR', 'Ubud', 'Jl. Suweta, Ubud', 1, 1, 200, 80, '["Rice Field View", "Plunge Pool", "Outdoor Bathtub", "Breakfast Included", "Spa Credit", "WiFi"]'::jsonb, '["/images/listings/romantic-rice-field-retreat-ubud-1.jpg", "/images/listings/romantic-rice-field-retreat-ubud-2.jpg", "/images/listings/romantic-rice-field-retreat-ubud-3.jpg"]'::jsonb, '/images/listings/romantic-rice-field-retreat-ubud-1.jpg', true, true);

INSERT INTO properties (owner_id, title, slug, description, property_type, listing_type, price, price_period, currency, area, address, bedrooms, bathrooms, land_size_sqm, building_size_sqm, features, images, thumbnail_url, is_active, is_featured) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Beachfront Holiday Home in Nusa Dua', 'beachfront-holiday-nusa-dua', 'Spacious 4-bedroom beachfront house available for weekly rental. Direct beach access, BBQ area, large garden, and ocean views from every room. Perfect for families and groups visiting Bali.', 'house', 'short_term_rent', 18000000, 'per_week', 'IDR', 'Nusa Dua', 'BTDC Area, Nusa Dua', 4, 3, 600, 350, '["Beachfront", "Ocean View", "BBQ Area", "Garden", "Parking", "Fully Equipped Kitchen"]'::jsonb, '["/images/listings/beachfront-holiday-nusa-dua-1.jpg", "/images/listings/beachfront-holiday-nusa-dua-2.jpg", "/images/listings/beachfront-holiday-nusa-dua-3.jpg"]'::jsonb, '/images/listings/beachfront-holiday-nusa-dua-1.jpg', true, true);
